name: services_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  provider: ^6.1.2
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_auth: ^5.0.0
  google_maps_flutter: ^2.7.0
  location: ^6.0.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  map_launcher: ^3.3.1
  photo_view: ^0.15.0
  saver_gallery: ^3.0.6
  share_plus: ^11.0.0
  emoji_picker_flutter: ^4.3.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  convex_bottom_bar: ^3.2.0
  package_info_plus: ^8.0.0
  flutter_sound: ^9.4.19
  permission_handler: ^11.3.1
  firebase_app_check: ^0.3.0
  flutter_animate: ^4.5.0
  just_audio: ^0.9.38
  wakelock_plus: ^1.2.5
  image_cropper: ^8.0.2
  image_painter: ^0.7.1
  audioplayers: ^6.0.0
  google_sign_in: ^7.1.1
  flutter_launcher_icons: ^0.14.4





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0

# إعدادات flutter_launcher_icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.jpg"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/salah1.jpeg
    - assets/images/default-map-preview-image.jpg
    - assets/background_images/blue-background.jpg
    - assets/icons/artisan.png
    - assets/images/logo.jpg
